# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8
        pip install -r requirements.txt

    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        set PYTHONPATH=it_hilfe
        set DATA=data
        python -m pytest --cov=it_hilfe
    - name: upadate coverage badge
      run: |
        cd .github
        python update_cov_badge.py
    - name: docbuild with sphinx
      run: |
        cd docs
        make html
    - name: built .exe with pyinstaller
      run: |
        pyinstaller --name "it_hilfe" --onefile --noconsole --icon ./data/favicon.ico ./it_hilfe/it_hilfe_gui2_logic.py
    - name: Archive doc html
      uses: actions/upload-artifact@v2
      with:
        name: it_hile_latest_html_doc
        path: ./docs/_build/html
    - name: Archive exe
      uses: actions/upload-artifact@v2
      with:
        name: it_hile_latest_exe
        path: ./dist/it_hilfe.exe

