# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
        
    - name: Get the percentage
      run: echo "COV=95" >> $GITHUB_ENV
      
    - name: Create the Badge if cov >= 90%
      if: ${{ env.COV }} >= 90
      uses: schneegans/dynamic-badges-action@v1.0.0
      with: 
        auth: ${{ secrets.GIST_TOKEN }}
        gistID: 5dfef24b289a9890e7d579140ca0ae15
        filename: test.json
        label: coverage
        message: ${{ env.COV }}
        color: green 
        
    - name: update the Badge if cov <= 90%
      if: ${{ env.ANSWER }} <= 90
      uses: schneegans/dynamic-badges-action@v1.0.0
      with:
        auth: ${{ secrets.GIST_TOKEN }}
        gistID: 5dfef24b289a9890e7d579140ca0ae15
        filename: test.json
        label: coverage
        message: ${{ env.COV }}
        color: orange 
          
          
          
          
